layout: sidebar
style: light

port: 4040

title: Christian Terjesen
description: "A passionate maker at the intersection of creativity and technology. My biggest adventure so far was founding and leading Adventure Audio, where I poured my passion into creating unique audio equipment for musicians and audiophiles. More recently, I've been working as a Technology Development Scientist for a private company, where I've been at the forefront of developing advanced X-ray and photon imaging technology and cameras for X-ray experiments at synchotron particle accelerators. I've even had the opportunity to run experiments at Cornell University. Services include Sound Design, Technical Writing, Audio Engineering, and Engineering Design. Associated with Sydor Technologies and the University of Rochester. Education includes University of Rochester and Rochester Institute of Technology, with a certification in Fundamentals of Audio and Music Engineering and various ECE courses."url: "http://christiant.is-a.dev"
baseurl: ""

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: :title/

author:
  name: Christian Terjesen

github:
  username: 8sevenCentral

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  limit: 36
# topics:
#   - name: CSS
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

#   - name: Web design

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
