layout: sidebar
style: light

port: 4040

title: Christian Terjesen
description: "A passionate maker at the intersection of creativity and technology. My journey began with a Bachelor of Arts in Music Arts Technology from Bloomfield College, NJ (now part of Montclair University), followed by a Master of Science in Electrical Engineering (MSEE) with a focus on Audio Technology from the University of Rochester. These foundational experiences honed my skills in everything from fundamental audio engineering to advanced Electrical and Computer Engineering concepts. After my studies, my biggest adventure so far was founding and leading Adventure Audio, where I poured my passion into creating unique audio equipment for musicians and audiophiles. This venture became a crucible for self-taught skills, encompassing everything from hands-on manufacturing processes like CNC machining, UV printing, powder coating, 3D printing, pick-and-place programming and operation, and screen printing, to the intricate details of electrical test assemblies and processes. I mastered manufacturing a product from start to finish (DFM), navigated international shipping trades, managed component sourcing, database management, payroll, business taxes and laws, and employee management. Beyond the business operations, I delved deep into website and webshop creation and maintenance, illustrative design, and, of course, all the core audio tech skills: designing PCBs, testing and simulating circuits, and crafting enclosures and UI/UX for our products. Unfortunately, the challenges brought on by COVID-19 forced us to close up shop, which ultimately led to my transition into the role of a Technology Development Scientist. More recently, I've been working as a Technology Development Scientist for a private company, where I've been at the forefront of developing advanced X-ray and photon imaging technology and cameras for X-ray experiments at synchotron particle accelerators. I've even had the opportunity to run experiments at Cornell University. Due to recent shifts in scientific research funding, I'm currently seeking a new adventure! I'm actively honing my skills in Python, exploring self-hosted open-source software for various applications, and diving deep into large language model implementation for audio technology development. Services include Sound Design, Technical Writing, Audio Engineering, and Engineering Design. Associated with Sydor Technologies and the University of Rochester."url: "http://christiant.is-a.dev"
baseurl: ""

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: :title/

author:
  name: Christian Terjesen

github:
  username: 8sevenCentral

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  limit: 36
# topics:
#   - name: CSS
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

#   - name: Web design

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
